# Generated by Django 5.1.3 on 2024-11-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_image', models.CharField(default='', max_length=500)),
                ('oven_temp', models.IntegerField(null=True)),
                ('serving_size', models.FloatField()),
                ('recipe_category', models.CharField(max_length=50)),
                ('recipe_tags', models.CharField(max_length=200)),
                ('recipe_instructions', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('ingredient_quanitiy', models.FloatField()),
                ('ingredient_measurement', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipe')),
            ],
        ),
    ]
