# Generated by Django 5.1.3 on 2024-11-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_recipe_likes_recipe_time_stamp_recipe_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_stamp',
            new_name='created_timestamp',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='updated',
            new_name='updated_timestamp',
        ),
    ]
