# Generated by Django 5.1.3 on 2024-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_rename_time_stamp_recipe_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='empty.jpg', upload_to='recipe_img'),
        ),
    ]
