# Generated by Django 5.1.3 on 2024-12-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='empty.jpg', upload_to='recipe_img'),
        ),
    ]
